import re
from openai import OpenAI
from rich.console import Console
from terminal_ai.config import Config
from terminal_ai.prompt_builder import build_system_prompt, build_explain_prompt

console = Console()

class NvidiaClient:
    def __init__(self):
        Config.validate()
        self.client = OpenAI(
            base_url=Config.BASE_URL,
            api_key=Config.API_KEY
        )
        self.model = Config.MODEL

    def _clean_command(self, raw_command: str) -> str:
        """
        Cleans the command returned by the LLM (removes markdown backticks, leading/trailing whitespace).
        """
        # Strip whitespaces
        cmd = raw_command.strip()
        
        # Remove triple backticks with optional language identifier (e.g. ```bash ... ```)
        pattern = r"^```[a-zA-Z0-9_\-+]*\n?(.*?)\n?```$"
        match = re.match(pattern, cmd, re.DOTALL)
        if match:
            cmd = match.group(1).strip()
            
        # Also remove inline backticks if they wrap the entire line
        if cmd.startswith("`") and cmd.endswith("`"):
            cmd = cmd[1:-1].strip()
            
        # Strip double quotes if the whole command was quoted (e.g. "find .")
        if (cmd.startswith('"') and cmd.endswith('"')) or (cmd.startswith("'") and cmd.endswith("'")):
            cmd = cmd[1:-1].strip()
            
        return cmd

    def generate_command(self, query: str, os_name: str, shell_name: str) -> str:
        """
        Calls NVIDIA NIM to generate a shell command from a natural language query.
        """
        system_prompt = build_system_prompt(os_name, shell_name)
        
        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": query}
                ],
                temperature=0.1,  # Low temperature for deterministic commands
                max_tokens=256
            )
            if not response.choices:
                raise ValueError("NVIDIA NIM API returned an empty response (no choices).")
            raw_command = response.choices[0].message.content
            if not raw_command:
                raise ValueError("NVIDIA NIM API returned an empty command content (possibly blocked by safety filters).")
            return self._clean_command(raw_command)
        except Exception as e:
            console.print(f"[bold red]API Error:[/bold red] {e}")
            raise

    def explain_command(self, command: str, os_name: str, shell_name: str) -> str:
        """
        Calls NVIDIA NIM to get an explanation of the given shell command.
        """
        explain_prompt = build_explain_prompt(command, os_name, shell_name)
        
        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": "You are a helpful shell command explanation assistant."},
                    {"role": "user", "content": explain_prompt}
                ],
                temperature=0.2,
                max_tokens=512
            )
            if not response.choices:
                raise ValueError("NVIDIA NIM API returned an empty response for explanation (no choices).")
            raw_explanation = response.choices[0].message.content
            if not raw_explanation:
                return "No explanation could be generated by the NVIDIA NIM API."
            return raw_explanation.strip()
        except Exception as e:
            console.print(f"[bold red]API Error during explanation:[/bold red] {e}")
            raise
